name: Build

on:
  push:
    branches:
    - 'main'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag
        uses: viostream/github-tag-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Write version
        run: |
          cat << EOF > cmd/version.go
          package cmd

          const Version = "${{ steps.tag.outputs.new_tag }}"
          EOF
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Make binaries
        run: |
          GOOS=linux go build -o fusion-theme-sync
          GOOS=windows go build -o fusion-theme-sync.exe
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: |
            fusion-theme-sync
            fusion-theme-sync.exe
