name: Test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          file: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
